apiVersion: v1
kind: Service
metadata:
  name: bin-calendar
  namespace: ns-bin-calendar
spec:
  selector:
    app: bin-calendar
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8000
  type: LoadBalancer
